### ISSUE TITLE
Perhaps you will update the repo in the future？

### ISSUE THREAD

**Issue by JinShuwenABC** [AiArt-HDU/MATEBIT#2]
Sorry to bother you. There is a problem during my running the code.

for class Pix2pixDataset, on data\pix2pix_dataset.py line 79 and 104, there is an assignment to val as follow.

`val = self.ref_dict[key]`

However, it is defined by self.get_ref(opt) on line 39, and the method self.get_ref() has nothing to do on line 131.

**Comment by JcccKing** [comment]
Hello, val = self.ref_dict[key] in pix2pixhd.py will be inherited from (Metfaces_dataset.py ...) .
