### ISSUE TITLE
CelebA dataset and instructions to train with my own dataset

### ISSUE THREAD

**Issue by chokevin8** [AiArt-HDU/MATEBIT#4]
Hi, first of all, thanks for your work. I'm trying to replicate it, but the CelebA download link may be incorrect, because when I try to run the train.py command as listed in your README, I get the error "FileNotFoundError: [Errno 2] No such file or directory: '/home/labuser1/PycharmProjects/MATEBIT/data/Dataset/CelebAMask-HQ/train.txt', and this is because there is no train.txt in the downloaded .zip file. Do I have to create one? 
Also, I eventually want to train this model using my own dataset, any instructions in how to do that? Thank you so much in advance!

**Comment by chokevin8** [comment]
Also, the google drive to link to download DeepFashion has permission issues as well.

**Comment by JcccKing** [comment]
Hello, for celeba, deepfashion dataset download, you can go to refer cocosnet paper(https://github.com/microsoft/CoCosNet-v2). For deepfashion, you may need to request an email from MMLab.
