### ISSUE TITLE
Import Error: cannot import name 'DynamicSparseTransformerBlock' from 'models.networks.dynast_transformer' 

### ISSUE THREAD

**Issue by Code-Author** [AiArt-HDU/MATEBIT#6]
I keep getting this error :
from models.networks.dynast_transformer import DynamicSparseTransformerBlock
ImportError: cannot import name 'DynamicSparseTransformerBlock' from 'models.networks.dynast_transformer'  (G:\My Drive\All_Deep_Learning_Models\MATEBIT-master\MATEBIT-master\models\networks\dynast_transformer.py)

how do I fix it ? I tried removing "'DynamicSparseTransformerBlock' from 'models.networks.dynast_transformer' "  that but then I just get 
but then I just get a different error.

**Comment by JcccKing** [comment]
yes

**Comment by aiartjc666** [comment]
you delete this import
